env_prefix              = "3-tier"
my-vpc-cidr             = "10.0.0.0/16"
pub_subnet_cidr         = ["10.0.1.0/24", "10.0.2.0/24"]
public_subnet_az        = ["ap-northeast-3a", "ap-northeast-3b"]
private_subnet_az       = ["ap-northeast-3a", "ap-northeast-3b"]
private_subnet_cidr     = ["10.0.3.0/24", "10.0.4.0/24"]
route_table_cidr        = "0.0.0.0/0"
ec2_instance_type       = "t2.micro"
region                  = "ap-northeast-3"
rds_allocated_storage   = "20"
rds_engine              = "mysql"
rds_engine_version      = "8.0.23"
rds_instance_class      = "db.t2.micro"
rds_multi_az            = true
rds_name                = "mydb"
rds_username            = "tarun"
rds_password            = "password"
rds_skip_final_snapshot = true
ec2_ami                 = "ami-04e1b6c20fd8a3fef"