variable "env_prefix" {}
variable "my-vpc-cidr" {}
variable "pub_subnet_cidr" {}
variable "public_subnet_az" {}
variable "private_subnet_cidr" {}
variable "route_table_cidr" {}
variable "ec2_instance_type" {}
variable "private_subnet_az" {}
variable "region" {}
variable "rds_allocated_storage" {}
variable "rds_engine" {}
variable "rds_engine_version" {}
variable "rds_instance_class" {}
variable "rds_name" {}
variable "rds_username" {}
variable "rds_password" {}
variable "rds_skip_final_snapshot" {}
variable "rds_multi_az" {}
variable "ec2_ami" {}

